"use client";

import {
  AlertOctagon,
  AlertTriangle,
  CheckCircle2,
  Clock3,
  Eye,
  LoaderCircle,
  ShieldAlert,
  ShieldCheck,
  Siren,
} from "lucide-react";

import { useSecurityAlerts } from "@/features/alerts/use-security-alerts";

function formatDate(value?: string | null) {
  if (!value) {
    return "—";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function getSeverityClass(severity: string) {
  const normalized = severity.toUpperCase();

  if (normalized === "CRITICAL") {
    return "border-red-500/30 bg-red-500/10 text-red-300";
  }

  if (normalized === "HIGH") {
    return "border-orange-500/30 bg-orange-500/10 text-orange-300";
  }

  if (normalized === "MEDIUM") {
    return "border-amber-500/30 bg-amber-500/10 text-amber-300";
  }

  return "border-slate-500/30 bg-slate-500/10 text-slate-300";
}

function getStatusClass(status: string) {
  const normalized = status.toUpperCase();

  if (normalized === "OPEN") {
    return "border-red-500/30 bg-red-500/10 text-red-300";
  }

  if (normalized === "INVESTIGATING") {
    return "border-amber-500/30 bg-amber-500/10 text-amber-300";
  }

  if (normalized === "RESOLVED" || normalized === "CLOSED") {
    return "border-emerald-500/30 bg-emerald-500/10 text-emerald-300";
  }

  return "border-slate-500/30 bg-slate-500/10 text-slate-300";
}

export default function AlertsPage() {
  const {
    data,
    isLoading,
    isError,
  } = useSecurityAlerts(1, 10);

  const alerts = data?.items ?? [];

  const openAlerts = alerts.filter(
    (alert) =>
      alert.status.toUpperCase() === "OPEN" ||
      alert.status.toUpperCase() === "INVESTIGATING",
  ).length;

  const criticalAlerts = alerts.filter(
    (alert) => alert.severity.toUpperCase() === "CRITICAL",
  ).length;

  const highAlerts = alerts.filter(
    (alert) => alert.severity.toUpperCase() === "HIGH",
  ).length;

  const resolvedAlerts = alerts.filter(
    (alert) =>
      alert.status.toUpperCase() === "RESOLVED" ||
      alert.status.toUpperCase() === "CLOSED",
  ).length;

  return (
    <div className="space-y-8">
      {/* Hero */}
      <section className="relative overflow-hidden rounded-3xl border border-slate-800 bg-[#0a0f16] p-6 sm:p-8">
        <div className="absolute -right-24 -top-24 h-64 w-64 rounded-full bg-red-500/10 blur-3xl" />
        <div className="absolute -bottom-24 left-1/3 h-48 w-48 rounded-full bg-cyan-500/5 blur-3xl" />

        <div className="relative">
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2 rounded-full border border-red-500/20 bg-red-500/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-red-300">
              <Siren className="h-3.5 w-3.5" />
              Incident Response
            </div>

            <div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">
              <ShieldCheck className="h-3.5 w-3.5" />
              Alert Pipeline Online
            </div>
          </div>

          <div className="mt-6 max-w-3xl">
            <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
              Alerts & Incidents
            </h1>

            <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400 sm:text-base">
              Investigate security alerts generated by SentinelX agents,
              policies, and runtime enforcement.
            </p>
          </div>

          <div className="mt-8 grid gap-3 sm:grid-cols-3">
            {[
              ["DETECT", "Identify suspicious activity"],
              ["TRIAGE", "Prioritize security alerts"],
              ["RESPOND", "Track incident resolution"],
            ].map(([title, description]) => (
              <div
                key={title}
                className="rounded-2xl border border-slate-800 bg-black/20 p-4"
              >
                <p className="text-[10px] font-bold tracking-[0.22em] text-cyan-400">
                  {title}
                </p>
                <p className="mt-2 text-sm text-slate-300">
                  {description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Metrics */}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center justify-between">
            <div className="rounded-xl bg-red-500/10 p-2.5">
              <AlertOctagon className="h-5 w-5 text-red-400" />
            </div>

            <span className="text-[10px] font-bold tracking-[0.18em] text-slate-600">
              ACTIVE
            </span>
          </div>

          <p className="mt-5 text-3xl font-semibold text-white">
            {data?.total ?? 0}
          </p>

          <p className="mt-1 text-sm text-slate-400">
            Total Alerts
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center justify-between">
            <div className="rounded-xl bg-orange-500/10 p-2.5">
              <ShieldAlert className="h-5 w-5 text-orange-400" />
            </div>

            <span className="text-[10px] font-bold tracking-[0.18em] text-orange-400">
              OPEN
            </span>
          </div>

          <p className="mt-5 text-3xl font-semibold text-white">
            {openAlerts}
          </p>

          <p className="mt-1 text-sm text-slate-400">
            Open Incidents
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center justify-between">
            <div className="rounded-xl bg-amber-500/10 p-2.5">
              <AlertTriangle className="h-5 w-5 text-amber-400" />
            </div>

            <span className="text-[10px] font-bold tracking-[0.18em] text-amber-400">
              PRIORITY
            </span>
          </div>

          <p className="mt-5 text-3xl font-semibold text-white">
            {criticalAlerts + highAlerts}
          </p>

          <p className="mt-1 text-sm text-slate-400">
            High Priority
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center justify-between">
            <div className="rounded-xl bg-emerald-500/10 p-2.5">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" />
            </div>

            <span className="text-[10px] font-bold tracking-[0.18em] text-emerald-400">
              CLOSED
            </span>
          </div>

          <p className="mt-5 text-3xl font-semibold text-white">
            {resolvedAlerts}
          </p>

          <p className="mt-1 text-sm text-slate-400">
            Resolved Alerts
          </p>
        </div>
      </section>

      {/* Alert registry */}
      <section className="overflow-hidden rounded-3xl border border-slate-800 bg-[#0a0f16]">
        <div className="flex flex-col gap-4 border-b border-slate-800 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6">
          <div>
            <div className="flex items-center gap-3">
              <h2 className="text-lg font-semibold text-white">
                Incident Queue
              </h2>

              <span className="rounded-full border border-slate-700 bg-slate-900 px-2.5 py-1 text-[10px] font-bold tracking-[0.15em] text-slate-400">
                {data?.total ?? 0} ALERTS
              </span>
            </div>

            <p className="mt-1 text-sm text-slate-500">
              Latest alerts requiring security operations attention
            </p>
          </div>

          <button
            type="button"
            className="flex w-fit items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-xs font-semibold text-slate-300 transition hover:border-cyan-500/30 hover:text-cyan-300"
          >
            <Eye className="h-4 w-4" />
            Review Queue
          </button>
        </div>

        {isLoading && (
          <div className="flex min-h-72 items-center justify-center">
            <div className="text-center">
              <LoaderCircle className="mx-auto h-8 w-8 animate-spin text-cyan-400" />

              <p className="mt-4 text-xs font-medium uppercase tracking-[0.2em] text-slate-500">
                Loading alert telemetry
              </p>
            </div>
          </div>
        )}

        {isError && !isLoading && (
          <div className="flex min-h-72 items-center justify-center p-6">
            <div className="max-w-md text-center">
              <AlertTriangle className="mx-auto h-9 w-9 text-red-400" />

              <h3 className="mt-4 text-sm font-semibold text-white">
                Alert telemetry unavailable
              </h3>

              <p className="mt-2 text-sm leading-6 text-slate-500">
                SentinelX could not retrieve the current security alert
                stream. Verify that the backend is running and authenticated.
              </p>
            </div>
          </div>
        )}

        {!isLoading && !isError && alerts.length === 0 && (
          <div className="flex min-h-72 items-center justify-center p-6">
            <div className="max-w-md text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-emerald-500/20 bg-emerald-500/10">
                <ShieldCheck className="h-7 w-7 text-emerald-400" />
              </div>

              <h3 className="mt-5 text-sm font-semibold text-white">
                No security alerts
              </h3>

              <p className="mt-2 text-sm leading-6 text-slate-500">
                The SentinelX control plane has not recorded any alerts for
                the current account.
              </p>

              <div className="mt-5 inline-flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-400">
                <CheckCircle2 className="h-3.5 w-3.5" />
                No active incidents
              </div>
            </div>
          </div>
        )}

        {!isLoading && !isError && alerts.length > 0 && (
          <div className="divide-y divide-slate-800/80">
            {alerts.map((alert) => (
              <div
                key={alert.id}
                className="group p-5 transition hover:bg-white/[0.02] sm:p-6"
              >
                <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between">
                  <div className="flex min-w-0 gap-4">
                    <div className="mt-0.5 rounded-xl border border-red-500/20 bg-red-500/10 p-2.5">
                      <Siren className="h-5 w-5 text-red-400" />
                    </div>

                    <div className="min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <h3 className="truncate text-sm font-semibold text-white">
                          {alert.title}
                        </h3>

                        <span
                          className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-[0.12em] ${getSeverityClass(
                            alert.severity,
                          )}`}
                        >
                          {alert.severity}
                        </span>
                      </div>

                      <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">
                        {alert.description || "No incident description provided."}
                      </p>

                      <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-slate-600">
                        <span className="flex items-center gap-1.5">
                          <span className="font-mono text-slate-500">
                            ALERT-{alert.id}
                          </span>
                        </span>

                        <span className="flex items-center gap-1.5">
                          <Clock3 className="h-3.5 w-3.5" />
                          {formatDate(alert.created_at)}
                        </span>

                        {alert.agent_id !== null &&
                          alert.agent_id !== undefined && (
                            <span>
                              Agent #{alert.agent_id}
                            </span>
                          )}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 xl:shrink-0">
                    <span
                      className={`rounded-full border px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.14em] ${getStatusClass(
                        alert.status,
                      )}`}
                    >
                      {alert.status}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* Operational posture */}
      <section className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-cyan-500/10 p-2.5">
              <Siren className="h-5 w-5 text-cyan-400" />
            </div>

            <div>
              <p className="text-sm font-semibold text-white">
                Detection Pipeline
              </p>
              <p className="text-xs text-slate-500">
                Alert generation operational
              </p>
            </div>
          </div>

          <div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-800">
            <div className="h-full w-full rounded-full bg-cyan-400" />
          </div>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-amber-500/10 p-2.5">
              <AlertTriangle className="h-5 w-5 text-amber-400" />
            </div>

            <div>
              <p className="text-sm font-semibold text-white">
                Priority Monitoring
              </p>
              <p className="text-xs text-slate-500">
                {criticalAlerts} critical · {highAlerts} high
              </p>
            </div>
          </div>

          <div className="mt-5 flex items-center gap-2 text-xs text-slate-500">
            <span className="h-2 w-2 rounded-full bg-amber-400" />
            Severity classification active
          </div>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-[#0a0f16] p-5">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-emerald-500/10 p-2.5">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" />
            </div>

            <div>
              <p className="text-sm font-semibold text-white">
                Response Tracking
              </p>
              <p className="text-xs text-slate-500">
                Incident lifecycle monitored
              </p>
            </div>
          </div>

          <div className="mt-5 flex items-center gap-2 text-xs text-emerald-400">
            <span className="h-2 w-2 rounded-full bg-emerald-400" />
            Resolution telemetry online
          </div>
        </div>
      </section>
    </div>
  );
}