"""Add Phase 15 incident and webhook schema

Revision ID: 07f5ee1f8924
Revises: 56e95f19bd7b
Create Date: 2026-10-03 12:51:34.246674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f5ee1f8924'
down_revision: Union[str, Sequence[str], None] = '56e95f19bd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_incident_alert', 'incident_alerts', ['incident_id', 'alert_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_incident_alert', 'incident_alerts', type_='unique')
    # ### end Alembic commands ###
