"""add risk scoring configurations

Revision ID: 62ca4acb55d8
Revises: f273c8016875
Create Date: 2026-10-05 22:30:30.737962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ca4acb55d8'
down_revision: Union[str, Sequence[str], None] = 'f273c8016875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scoring_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('blocked_event_weight', sa.Integer(), nullable=False),
    sa.Column('suspicious_event_weight', sa.Integer(), nullable=False),
    sa.Column('policy_violation_weight', sa.Integer(), nullable=False),
    sa.Column('score_cap', sa.Integer(), nullable=False),
    sa.Column('low_max', sa.Integer(), nullable=False),
    sa.Column('medium_max', sa.Integer(), nullable=False),
    sa.Column('high_max', sa.Integer(), nullable=False),
    sa.Column('critical_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scoring_configurations_enabled'), 'risk_scoring_configurations', ['enabled'], unique=False)
    op.create_index(op.f('ix_risk_scoring_configurations_id'), 'risk_scoring_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scoring_configurations_owner_id'), 'risk_scoring_configurations', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scoring_configurations_owner_id'), table_name='risk_scoring_configurations')
    op.drop_index(op.f('ix_risk_scoring_configurations_id'), table_name='risk_scoring_configurations')
    op.drop_index(op.f('ix_risk_scoring_configurations_enabled'), table_name='risk_scoring_configurations')
    op.drop_table('risk_scoring_configurations')
    # ### end Alembic commands ###
