"""add detection rules

Revision ID: 81b0f76c34f8
Revises: 07f5ee1f8924
Create Date: 2026-10-05 22:02:05.530394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b0f76c34f8'
down_revision: Union[str, Sequence[str], None] = '07f5ee1f8924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_alert_type'), 'detection_rules', ['alert_type'], unique=False)
    op.create_index(op.f('ix_detection_rules_enabled'), 'detection_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_detection_rules_id'), 'detection_rules', ['id'], unique=False)
    op.create_index(op.f('ix_detection_rules_owner_id'), 'detection_rules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_detection_rules_severity'), 'detection_rules', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_rules_severity'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_owner_id'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_id'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_enabled'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_alert_type'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
