
"use client";

import {
  Activity,
  AlertTriangle,
  Ban,
  CheckCircle2,
  Clock3,
  Filter,
  LoaderCircle,
  ShieldAlert,
  ShieldCheck,
  Terminal,
} from "lucide-react";

import { useSecurityEvents } from "@/features/events/use-security-events";

function DecisionBadge({ decision }: { decision: string }) {
  const normalized = decision.toUpperCase();
  const blocked = normalized.includes("BLOCK");
  const warning = normalized.includes("WARN");

  const style = blocked
    ? "border-red-400/15 bg-red-400/[0.06] text-red-300"
    : warning
      ? "border-amber-400/15 bg-amber-400/[0.06] text-amber-300"
      : "border-emerald-400/15 bg-emerald-400/[0.06] text-emerald-300";

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[8px] font-semibold uppercase tracking-[0.14em] ${style}`}
    >
      {blocked ? (
        <Ban className="size-3" />
      ) : warning ? (
        <AlertTriangle className="size-3" />
      ) : (
        <CheckCircle2 className="size-3" />
      )}
      {normalized}
    </span>
  );
}

function formatDate(value: string) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "—";
  }

  return date.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function EventsPage() {
  const { data, isLoading, isError } = useSecurityEvents(1, 10);

  const events = data?.items ?? [];
  const total = data?.total ?? 0;

  const blockedCount = events.filter((event) =>
    event.decision.toUpperCase().includes("BLOCK"),
  ).length;

  const warningCount = events.filter((event) =>
    event.decision.toUpperCase().includes("WARN"),
  ).length;

  const allowedCount = events.filter(
    (event) =>
      !event.decision.toUpperCase().includes("BLOCK") &&
      !event.decision.toUpperCase().includes("WARN"),
  ).length;

  const streamState = isLoading
    ? "Synchronizing"
    : isError
      ? "Degraded"
      : "Operational";

  return (
    <div className="space-y-5">
      {/* Header */}
      <section className="security-surface relative overflow-hidden p-5 sm:p-6">
        <div className="security-grid pointer-events-none absolute inset-0 opacity-25" />

        <div className="relative">
          <div className="flex flex-wrap items-center gap-2">
            <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-400">
              <Activity className="size-3.5" />
              Security Telemetry
            </div>

            <span className="h-1 w-1 rounded-full bg-slate-700" />

            <span className="font-mono text-[9px] uppercase tracking-[0.16em] text-slate-600">
              Runtime / Events
            </span>
          </div>

          <div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <h1 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">
                Security Events
              </h1>

              <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">
                Investigate security decisions generated by SentinelX agents,
                policies, and runtime enforcement.
              </p>
            </div>

            <StreamIndicator state={streamState} isError={isError} />
          </div>
        </div>
      </section>

      {/* Metrics */}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard
          label="Total Events"
          value={isLoading ? "—" : isError ? "!" : total.toString()}
          detail="Recorded security activity"
          icon={Activity}
          tone="cyan"
        />

        <MetricCard
          label="Blocked"
          value={isLoading ? "—" : isError ? "!" : blockedCount.toString()}
          detail="Actions prevented"
          icon={Ban}
          tone="red"
        />

        <MetricCard
          label="Warnings"
          value={isLoading ? "—" : isError ? "!" : warningCount.toString()}
          detail="Actions requiring attention"
          icon={AlertTriangle}
          tone="amber"
        />

        <MetricCard
          label="Allowed"
          value={isLoading ? "—" : isError ? "!" : allowedCount.toString()}
          detail="Actions permitted"
          icon={ShieldCheck}
          tone="emerald"
        />
      </section>

      {/* Event stream */}
      <section className="security-surface overflow-hidden">
        <div className="flex flex-col gap-3 border-b border-white/[0.06] px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <div className="flex size-7 items-center justify-center rounded-lg border border-cyan-400/10 bg-cyan-400/[0.05]">
                <Activity className="size-3.5 text-cyan-300" />
              </div>

              <h2 className="text-sm font-semibold text-slate-200">
                Event Stream
              </h2>
            </div>

            <p className="mt-1 text-[10px] text-slate-600">
              Latest security events from the control plane
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="font-mono text-[9px] uppercase tracking-[0.14em] text-slate-600">
              Page
            </span>

            <span className="rounded-md border border-white/[0.06] bg-white/[0.025] px-2.5 py-1 font-mono text-[10px] text-slate-400">
              01 / {data?.pages ?? "—"}
            </span>

            <button
              type="button"
              aria-label="Filter security events"
              className="flex items-center gap-2 rounded-md border border-white/[0.06] bg-white/[0.025] px-2.5 py-1.5 text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-500 transition-colors hover:border-cyan-400/15 hover:text-cyan-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/40"
            >
              <Filter className="size-3" />
              Filter
            </button>
          </div>
        </div>

        {isLoading ? (
          <EventsLoadingState />
        ) : isError ? (
          <EventsErrorState />
        ) : events.length === 0 ? (
          <EventsEmptyState />
        ) : (
          <div className="divide-y divide-white/[0.05]">
            {events.map((event, index) => (
              <EventRow
                key={event.id}
                event={event}
                index={index}
              />
            ))}
          </div>
        )}
      </section>

      {/* Operational footer */}
      <section className="grid gap-3 md:grid-cols-3">
        <OperationalSignal
          icon={Activity}
          label="Telemetry stream"
          value={isError ? "Degraded" : "Operational"}
          detail="Security events available"
          tone={isError ? "red" : "cyan"}
        />

        <OperationalSignal
          icon={ShieldCheck}
          label="Decision engine"
          value="Active"
          detail="Runtime decisions recorded"
          tone="emerald"
        />

        <OperationalSignal
          icon={Clock3}
          label="Event retention"
          value={total.toString()}
          detail="Events currently indexed"
          tone="cyan"
        />
      </section>
    </div>
  );
}

function StreamIndicator({
  state,
  isError,
}: {
  state: string;
  isError: boolean;
}) {
  const tone = isError
    ? "red"
    : state === "Synchronizing"
      ? "amber"
      : "emerald";

  const classes = {
    red: "border-red-400/15 bg-red-400/[0.05] text-red-300",
    amber: "border-amber-400/15 bg-amber-400/[0.05] text-amber-300",
    emerald:
      "border-emerald-400/15 bg-emerald-400/[0.05] text-emerald-300",
  }[tone];

  const dot = {
    red: "bg-red-400",
    amber: "bg-amber-400",
    emerald: "bg-emerald-400",
  }[tone];

  return (
    <div
      className={`inline-flex w-fit items-center gap-2 rounded-full border px-3 py-1.5 ${classes}`}
    >
      <span
        className={`size-1.5 rounded-full ${dot} ${
          state === "Operational" ? "animate-pulse" : ""
        }`}
      />

      <span className="text-[9px] font-semibold uppercase tracking-[0.16em]">
        Stream {state}
      </span>
    </div>
  );
}

function MetricCard({
  label,
  value,
  detail,
  icon: Icon,
  tone,
}: {
  label: string;
  value: string;
  detail: string;
  icon: typeof Activity;
  tone: "cyan" | "red" | "amber" | "emerald";
}) {
  const styles = {
    cyan: {
      icon: "border-cyan-400/10 bg-cyan-400/[0.05] text-cyan-300",
      value: "text-white",
    },
    red: {
      icon: "border-red-400/10 bg-red-400/[0.05] text-red-300",
      value: "text-red-300",
    },
    amber: {
      icon: "border-amber-400/10 bg-amber-400/[0.05] text-amber-300",
      value: "text-amber-300",
    },
    emerald: {
      icon: "border-emerald-400/10 bg-emerald-400/[0.05] text-emerald-300",
      value: "text-emerald-300",
    },
  }[tone];

  return (
    <div className="security-surface security-surface-hover p-4">
      <div className="flex items-start justify-between gap-3">
        <span className="text-[9px] font-semibold uppercase tracking-[0.17em] text-slate-600">
          {label}
        </span>

        <div
          className={`flex size-8 shrink-0 items-center justify-center rounded-lg border ${styles.icon}`}
        >
          <Icon className="size-4" />
        </div>
      </div>

      <div
        className={`mt-4 text-2xl font-semibold tracking-tight ${styles.value}`}
      >
        {value}
      </div>

      <p className="mt-1 text-[10px] text-slate-600">{detail}</p>
    </div>
  );
}

function EventRow({
  event,
  index,
}: {
  event: {
    id: number;
    agent_id: number;
    policy_id?: number | null;
    event_type: string;
    action?: string | null;
    decision: string;
    reason?: string | null;
    created_at: string;
  };
  index: number;
}) {
  const normalized = event.decision.toUpperCase();
  const blocked = normalized.includes("BLOCK");
  const warning = normalized.includes("WARN");

  const accent = blocked
    ? "border-l-red-400/60"
    : warning
      ? "border-l-amber-400/60"
      : "border-l-emerald-400/50";

  const iconStyle = blocked
    ? "border-red-400/10 bg-red-400/[0.04] text-red-300"
    : warning
      ? "border-amber-400/10 bg-amber-400/[0.04] text-amber-300"
      : "border-cyan-400/10 bg-cyan-400/[0.04] text-cyan-300";

  return (
    <article
      className={`group border-l-2 ${accent} px-5 py-4 transition-colors hover:bg-white/[0.015]`}
    >
      <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex min-w-0 items-start gap-3">
          <div
            className={`flex size-9 shrink-0 items-center justify-center rounded-lg border ${iconStyle}`}
          >
            {blocked ? (
              <Ban className="size-4" />
            ) : warning ? (
              <AlertTriangle className="size-4" />
            ) : (
              <Activity className="size-4" />
            )}
          </div>

          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <span className="font-mono text-[9px] text-slate-700">
                EVT-{String(index + 1).padStart(2, "0")}
              </span>

              <span className="text-[9px] uppercase tracking-[0.12em] text-slate-700">
                #{event.id}
              </span>

              <DecisionBadge decision={event.decision} />
            </div>

            <h3 className="mt-1 truncate text-sm font-semibold text-slate-200">
              {event.event_type}
            </h3>

            <p className="mt-1 max-w-2xl truncate text-[10px] text-slate-600">
              {event.reason || "No decision reason recorded"}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-x-7 gap-y-3 sm:grid-cols-4 xl:min-w-[520px]">
          <EventMetadata
            label="Agent"
            value={`#${event.agent_id}`}
          />

          <EventMetadata
            label="Action"
            value={event.action || "No action recorded"}
          />

          <EventMetadata
            label="Policy"
            value={event.policy_id ? `#${event.policy_id}` : "None"}
          />

          <EventMetadata
            label="Timestamp"
            value={formatDate(event.created_at)}
            icon
          />
        </div>
      </div>
    </article>
  );
}

function EventMetadata({
  label,
  value,
  icon = false,
}: {
  label: string;
  value: string;
  icon?: boolean;
}) {
  return (
    <div className="min-w-0">
      <div className="flex items-center gap-1.5 text-[8px] font-medium uppercase tracking-[0.14em] text-slate-700">
        {icon && <Clock3 className="size-3" />}
        {label}
      </div>

      <div className="mt-1 truncate font-mono text-[10px] text-slate-400">
        {value}
      </div>
    </div>
  );
}

function OperationalSignal({
  icon: Icon,
  label,
  value,
  detail,
  tone,
}: {
  icon: typeof Activity;
  label: string;
  value: string;
  detail: string;
  tone: "cyan" | "emerald" | "red";
}) {
  const style = {
    cyan: "border-cyan-400/10 bg-cyan-400/[0.04] text-cyan-300",
    emerald:
      "border-emerald-400/10 bg-emerald-400/[0.04] text-emerald-300",
    red: "border-red-400/10 bg-red-400/[0.04] text-red-300",
  }[tone];

  return (
    <div className="security-surface flex items-center gap-3 p-4">
      <div
        className={`flex size-9 shrink-0 items-center justify-center rounded-lg border ${style}`}
      >
        <Icon className="size-4" />
      </div>

      <div className="min-w-0">
        <p className="text-[9px] font-semibold uppercase tracking-[0.15em] text-slate-600">
          {label}
        </p>

        <div className="mt-1 flex items-center gap-2">
          <span className="text-xs font-semibold text-slate-200">
            {value}
          </span>

          <span className="truncate text-[9px] text-slate-700">
            {detail}
          </span>
        </div>
      </div>
    </div>
  );
}

function EventsLoadingState() {
  return (
    <div className="flex min-h-72 flex-col items-center justify-center">
      <div className="flex size-10 items-center justify-center rounded-xl border border-cyan-400/10 bg-cyan-400/[0.04]">
        <LoaderCircle className="size-5 animate-spin text-cyan-400" />
      </div>

      <p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">
        Synchronizing telemetry
      </p>

      <p className="mt-1 text-[10px] text-slate-700">
        Reading current security event stream
      </p>
    </div>
  );
}

function EventsErrorState() {
  return (
    <div className="flex min-h-72 flex-col items-center justify-center px-6 text-center">
      <div className="flex size-11 items-center justify-center rounded-xl border border-red-400/10 bg-red-400/[0.04]">
        <ShieldAlert className="size-5 text-red-300" />
      </div>

      <p className="mt-4 text-sm font-medium text-slate-300">
        Event stream unavailable
      </p>

      <p className="mt-1 max-w-md text-[10px] leading-5 text-slate-600">
        SentinelX could not retrieve the security event stream. Verify the
        security session and control-plane connection.
      </p>
    </div>
  );
}

function EventsEmptyState() {
  return (
    <div className="relative flex min-h-72 flex-col items-center justify-center overflow-hidden px-6 text-center">
      <div className="security-grid pointer-events-none absolute inset-0 opacity-20" />

      <div className="relative flex size-14 items-center justify-center rounded-2xl border border-cyan-400/10 bg-cyan-400/[0.04]">
        <Terminal className="size-6 text-cyan-300/70" />
      </div>

      <p className="relative mt-4 text-sm font-semibold text-slate-300">
        No security events yet
      </p>

      <p className="relative mt-1 max-w-sm text-[10px] leading-5 text-slate-600">
        Events will appear here when SentinelX evaluates actions from
        registered agents.
      </p>

      <div className="relative mt-5 flex items-center gap-2 rounded-full border border-white/[0.05] bg-white/[0.02] px-3 py-1.5">
        <span className="size-1.5 rounded-full bg-slate-600" />

        <span className="font-mono text-[9px] uppercase tracking-[0.14em] text-slate-600">
          Telemetry awaiting events
        </span>
      </div>
    </div>
  );
}
