"use client";

import {
  Activity,
  AlertTriangle,
  Ban,
  CheckCircle2,
  Clock3,
  Filter,
  LoaderCircle,
  ShieldAlert,
  ShieldCheck,
  Terminal,
} from "lucide-react";

import { useSecurityEvents } from "@/features/events/use-security-events";

function DecisionBadge({ decision }: { decision: string }) {
  const normalized = decision.toUpperCase();

  const blocked = normalized.includes("BLOCK");
  const warning = normalized.includes("WARN");

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[9px] font-semibold tracking-[0.14em] ${
        blocked
          ? "border-red-400/20 bg-red-400/10 text-red-300"
          : warning
            ? "border-amber-400/20 bg-amber-400/10 text-amber-300"
            : "border-emerald-400/20 bg-emerald-400/10 text-emerald-300"
      }`}
    >
      {blocked ? (
        <Ban className="h-3 w-3" />
      ) : warning ? (
        <AlertTriangle className="h-3 w-3" />
      ) : (
        <CheckCircle2 className="h-3 w-3" />
      )}

      {normalized}
    </span>
  );
}

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export default function EventsPage() {
  const {
    data,
    isLoading,
    isError,
  } = useSecurityEvents(1, 10);

  const events = data?.items ?? [];
  const total = data?.total ?? 0;

  const blockedCount = events.filter((event) =>
    event.decision.toUpperCase().includes("BLOCK"),
  ).length;

  const warningCount = events.filter((event) =>
    event.decision.toUpperCase().includes("WARN"),
  ).length;

  const allowedCount = events.filter(
    (event) =>
      !event.decision.toUpperCase().includes("BLOCK") &&
      !event.decision.toUpperCase().includes("WARN"),
  ).length;

  return (
    <div className="space-y-8">
      {/* HERO */}
      <section className="relative overflow-hidden rounded-3xl border border-blue-400/10 bg-gradient-to-br from-blue-400/[0.08] via-transparent to-cyan-500/[0.05] p-6 sm:p-8">
        <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-blue-400/10 blur-3xl" />

        <div className="relative">
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1.5 text-xs font-medium text-blue-300">
              <Activity className="h-3.5 w-3.5" />
              Security Telemetry
            </div>

            <div className="flex items-center gap-2 text-xs text-emerald-400">
              <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" />
              Event stream operational
            </div>
          </div>

          <h1 className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
            Security Events
          </h1>

          <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">
            Investigate security decisions generated by SentinelX
            agents, policies, and runtime enforcement.
          </p>
        </div>
      </section>

      {/* METRICS */}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">
                Total Events
              </p>

              <p className="mt-3 text-3xl font-semibold text-white">
                {isLoading ? "—" : total}
              </p>

              <p className="mt-1 text-xs text-slate-500">
                Recorded security activity
              </p>
            </div>

            <Activity className="h-5 w-5 text-cyan-300" />
          </div>
        </div>

        <div className="rounded-2xl border border-red-400/10 bg-red-400/[0.035] p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-red-300/60">
                Blocked
              </p>

              <p className="mt-3 text-3xl font-semibold text-red-300">
                {isLoading ? "—" : blockedCount}
              </p>

              <p className="mt-1 text-xs text-slate-500">
                Actions prevented
              </p>
            </div>

            <Ban className="h-5 w-5 text-red-300" />
          </div>
        </div>

        <div className="rounded-2xl border border-amber-400/10 bg-amber-400/[0.035] p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-amber-300/60">
                Warnings
              </p>

              <p className="mt-3 text-3xl font-semibold text-amber-300">
                {isLoading ? "—" : warningCount}
              </p>

              <p className="mt-1 text-xs text-slate-500">
                Actions requiring attention
              </p>
            </div>

            <AlertTriangle className="h-5 w-5 text-amber-300" />
          </div>
        </div>

        <div className="rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.035] p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-emerald-300/60">
                Allowed
              </p>

              <p className="mt-3 text-3xl font-semibold text-emerald-300">
                {isLoading ? "—" : allowedCount}
              </p>

              <p className="mt-1 text-xs text-slate-500">
                Actions permitted
              </p>
            </div>

            <ShieldCheck className="h-5 w-5 text-emerald-300" />
          </div>
        </div>
      </section>

      {/* EVENT TABLE */}
      <section className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]">
        <div className="flex flex-col gap-4 border-b border-white/10 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="font-semibold text-white">
              Event Stream
            </h2>

            <p className="mt-1 text-xs text-slate-500">
              Latest security events from the control plane
            </p>
          </div>

          <button
            type="button"
            className="flex w-fit items-center gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-slate-400 transition hover:border-cyan-400/20 hover:text-cyan-300"
          >
            <Filter className="h-3.5 w-3.5" />
            Filter
          </button>
        </div>

        {isLoading ? (
          <div className="flex min-h-64 items-center justify-center">
            <div className="flex items-center gap-2 text-sm text-slate-500">
              <LoaderCircle className="h-4 w-4 animate-spin" />
              Loading security events...
            </div>
          </div>
        ) : isError ? (
          <div className="flex min-h-64 items-center justify-center px-6 text-center">
            <div>
              <ShieldAlert className="mx-auto h-8 w-8 text-red-400" />

              <h3 className="mt-4 font-semibold text-white">
                Unable to load events
              </h3>

              <p className="mt-2 text-sm text-slate-500">
                The security event service could not be reached.
              </p>
            </div>
          </div>
        ) : events.length === 0 ? (
          <div className="flex min-h-64 items-center justify-center px-6 text-center">
            <div>
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-blue-400/15 bg-blue-400/10">
                <Terminal className="h-6 w-6 text-blue-300" />
              </div>

              <h3 className="mt-4 font-semibold text-white">
                No security events yet
              </h3>

              <p className="mt-2 max-w-md text-sm leading-6 text-slate-500">
                Events will appear here when SentinelX evaluates
                actions from registered agents.
              </p>
            </div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[760px]">
              <thead>
                <tr className="border-b border-white/5 text-left">
                  <th className="px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-600">
                    Event
                  </th>

                  <th className="px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-600">
                    Agent
                  </th>

                  <th className="px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-600">
                    Action
                  </th>

                  <th className="px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-600">
                    Decision
                  </th>

                  <th className="px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-600">
                    Time
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-white/5">
                {events.map((event) => (
                  <tr
                    key={event.id}
                    className="transition hover:bg-white/[0.02]"
                  >
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-3">
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-cyan-400/10 bg-cyan-400/5 text-cyan-300">
                          <Activity className="h-4 w-4" />
                        </div>

                        <div>
                          <p className="text-sm font-medium text-white">
                            {event.event_type}
                          </p>

                          <p className="mt-0.5 text-[10px] text-slate-600">
                            Event #{event.id}
                          </p>
                        </div>
                      </div>
                    </td>

                    <td className="px-5 py-4 text-sm text-slate-400">
                      Agent #{event.agent_id}
                    </td>

                    <td className="px-5 py-4 text-sm text-slate-400">
                      {event.action || "—"}
                    </td>

                    <td className="px-5 py-4">
                      <DecisionBadge decision={event.decision} />
                    </td>

                    <td className="px-5 py-4">
                      <div className="flex items-center gap-2 text-xs text-slate-500">
                        <Clock3 className="h-3.5 w-3.5" />
                        {formatDate(event.created_at)}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}